config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'users#show'
  resources :start_days, only: [:new, :create]
  resources :count_times, only: [:new, :create, :edit, :update, :destroy]
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/count_time.rb
class CountTime < ApplicationRecord
  belongs_to :user
  # 5件のレコードを取得する
  def self.get_user_time_desc_5
    self.order("created_at DESC").limit(5)
  end
  # 昨日のレコードを取得する
  def self.get_yesterday_hour
    self.where("DATE(created_at) = ?", Date.today-1)
  end
  # 先週1週間のレコードを取得し、合計時間を計算する
  def self.get_last_monday_to_sunday
    self.where(created_at: (Date.today - 1.week).beginning_of_week..(Date.today - 1.week).end_of_week.end_of_day).sum(:count_hour)
  end
  # 今週1週間のレコードを取得し、合計時間をパーセントに計算する
  def self.get_percent_this_week
    self.where(created_at: Date.today.beginning_of_week..Date.today.end_of_week.end_of_day).sum(:count_hour)
  end
end

app/models/start_day.rb
class StartDay < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one :start_day, dependent: :destroy
  has_many :count_time, dependent: :destroy

  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/count_times_controller.rb
class CountTimesController < ApplicationController
  before_action :set_count_time, only: [:edit, :update, :destroy]

  def new
    @count_time = CountTime.new
  end

  def create
    @count_time = CountTime.create(count_time_params)
    if @count_time.save
      redirect_to :root
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @count_time.user_id == current_user.id
      if @count_time.update(count_time_params)
        redirect_to :root
      else
        render :edit
      end
    end
  end

  def destroy
    if @count_time.destroy
      redirect_to :root
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def count_time_params
    params.require(:count_time).permit(:count_hour).merge(user_id: current_user.id)
  end

  def set_count_time
    @count_time = CountTime.find(params[:id])
  end
end

app/controllers/start_days_controller.rb
class StartDaysController < ApplicationController

  def new
    # Start_day= スネークケースは使用不可
    # Start_day = StartDayキャメルケースに変換
    @start_day = StartDay.new
  end

  def create
    @start_day = StartDay.create(start_day_params)
    if @start_day.save
      redirect_to :root
    else
      render :new
    end
  end

  private

  def start_day_params
    params.require(:start_day).permit(:start_day).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @start_day = StartDay.where(user_id: current_user.id)
    # ログインユーザーのレコードを取得する
    @current_user = CountTime.where(user_id: current_user.id)
    @today_count_time = @current_user.limit(1)
    @count_time = @current_user.get_user_time_desc_5
    @count_hour = @count_time.sum(:count_hour)
    # 昨日の学習時間を計算するメソッド
    @yesterday = @current_user.get_yesterday_hour
    # 初期値リセット
    @yesterday_study_hour = 0
    # @yesterday_study_hourに昨日の学習時間の合計を足すメソッド
    @yesterday.each do |study|
      @yesterday_study_hour += study.count_hour
    end
    @word = {:nonClear => "今日は頑張りましょう !", :clear => "昨日は目標達成!"}
    # 平日と休日の勉強時間をハッシュでセットする
    @day_of_week = {:weekday => 3, :holiday => 5}
    @weekday_result = @day_of_week[:weekday] - @yesterday_study_hour
    @holiday_result = @day_of_week[:holiday] - @yesterday_study_hour
  end

  def a_year_counts
    # 年毎に合計するメソッド
    # 戻り値はハッシュ
    @a_year_counts = @current_user.group("YEAR(created_at)").sum(:count_hour)
  end

  def performance_this_year
    # 今年の合計時間を計算するメソッド
    this_year_performance = @current_user.where(created_at: Date.today.all_month).sum(:count_hour)
    # this_month_count = Date.today.all_month.count
    # total_study_time_in_week = (@day_of_week[:weekday] * 5) + (@day_of_week[:holiday] * 2)
    # this_year_goal = total_study_time_in_week * 4.4
    return "今月の目標は#{this_year_performance}/100時間"
  end

  def last_week_counts
    # 先週1週間の合計count_hourを計算するメソッド
    @last_week_counts = @current_user.get_last_monday_to_sunday
  end

  def percent_in_week
    # 今週1週間の合計count_hourを計算するメソッド
    @a_week_counts = @current_user.get_percent_this_week
    # 1週間の目標count_hourを計算するメソッド
    @total_study_time_in_week = (@day_of_week[:weekday] * 5) + (@day_of_week[:holiday] * 2)
    @percent_in_week = @a_week_counts.to_f / @total_study_time_in_week.to_f * 100
    gon.percent_in_week = @percent_in_week
  end

  def this_week_counts
    return "#{@a_week_counts} / #{@total_study_time_in_week}"
  end

  def duration_days
    # 継続日数メソッド
    continued = @current_user
    @duration_days = 0

    if continued.select("id").where(created_at: 0.day.ago.all_day).blank?
        i = 1
    else
        i = 0
    end

    while continued.length do
      unless continued.select("id").where(created_at: i.day.ago.all_day).blank?
        @duration_days += 1
        i += 1
      else
        countinuedExit = false
      end
      if countinuedExit == false
        break
      end
    end
    return @duration_days
  end

  def saturday_goal
    # @weekday_result = @day_of_week[:weekday] - @yesterday_study_hour
    if @yesterday_study_hour >= @day_of_week[:weekday]
      "#{@word[:clear]}今日の学習時間は#{@day_of_week[:holiday]}時間です！"
    else
      "今日の学習時間は#{@day_of_week[:holiday]}時間です！昨日は#{@weekday_result}時間足りませんでした！#{@word[:nonClear]}"
    end
  end

  def sunday_goal
    # @holiday_result = @day_of_week[:holiday] - @yesterday_study_hour
    if @yesterday_study_hour >= @day_of_week[:holiday]
      "#{@word[:clear]}今日の学習時間は#{@day_of_week[:holiday]}時間です！"
    else
      "今日の学習時間は#{@day_of_week[:holiday]}時間です！昨日は#{@holiday_result}時間足りませんでした！#{@word[:nonClear]}"
    end
  end

  def monday_goal
    # @holiday_result = @day_of_week[:holiday] - @yesterday_study_hour
    if @yesterday_study_hour >= @day_of_week[:holiday]
      "#{@word[:clear]}今日の学習時間は#{@@day_of_week[:weekday]}時間です"
    else
      "今日の学習時間は#{@day_of_week[:weekday]}時間です！昨日は#{@holiday_result}時間足りませんでした！#{@word[:nonClear]}"
    end
  end

  def otherDay_goal
    # @weekday_result = @day_of_week[:weekday] - @yesterday_study_hour
    if @yesterday_study_hour >= @day_of_week[:weekday]
      "#{@word[:clear]}今日の学習時間は#{@day_of_week[:weekday]}時間です！"
    else
      "今日の学習時間は#{@day_of_week[:weekday]}時間です！昨日は#{@weekday_result}時間足りませんでした！#{@word[:nonClear]}"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/count_times_helper.rb
module CountTimesHelper
end

app/helpers/start_days_helper.rb
module StartDaysHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/count_times/edit.html.erb
<h1 class='main_title'>今日の学習時間</h1>
<article class='l_container'>
  <section class='m_container new'>
    <%= form_for @count_time, url:{ action: 'update' } do |f| %>
      <%= f.number_field :count_hour, step: '0.1', class:'input_form' %>
      <%= f.submit '登録', class:'btn-primary' %>
    <% end %>
  </section>
</article>

app/views/count_times/new.html.erb
<h1 class='main_title'>今日の学習時間</h1>
<article class='l_container'>
  <section class='m_container new'>
    <%= form_for @count_time do |f| %>
      <%= f.number_field :count_hour, step: '0.1', class:'input_form' %>
      <%= f.submit '登録', class:'btn-primary' %>
    <% end %>
  </section>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyTimer</title>
    <%= Gon::Base.render_data %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/start_days/_aside.html.erb
<h3 class='nickname'><%= current_user.email if signed_in? %></h3>
<a class='duration_circle'>
  <span>継続日数<br><%= @Durationdays %>日</span>
</a>
<%= render 'button' %>

app/views/start_days/_table.html.erb
<div class='section'>
  <h2 class='section__title'>昨日までの学習時間</h2>
  <table>
    <tr>
      <th>日付</th>
      <th>時間</th>
    </tr>
    <% @count_time.each do |count_time| %>
      <tr>
        <td><%= count_time.created_at.to_date %></td>
        <td><%= count_time.count_hour %>時間</td>
      </tr>
    <% end %>
  </table>
</div>

app/views/start_days/index.html.erb
<main>
  <% if signed_in? %>

    <article class='l_container'>
      <section class='m_container'>
        <%= render 'section' %>
        <%= render 'table' %>
      </section>
    </article>
    <aside class='m_container_right'>
      <%= render 'aside' %>
    </aside>

  <%else %>

    <h1>あなたの学習時間</h1>
    <div class='button_section before_login'>
      <button class='user_btn'>
        <%= link_to 'ログイン', user_session_path, class:'user_link' %>
      </button>
    </div>

  <% end %>
</main>

app/views/start_days/new.html.erb
<h1 class='main_title'>今日の学習時間</h1>
<article class='l_container'>
  <section class='m_container new'>
    <%= form_for @start_day do |f| %>
      <%= f.label :学習開始日, class:'hoge' %>
      <%= f.text_field :start_day, id:'datepicker' %>
      <%= f.submit '登録' %>
    <% end %>
  </section>
</article>

app/views/users/_aside.html.erb
<a class='duration_circle'>
  <span>継続日数<br><%= controller.duration_days %>日</span>
</a>
<%= render 'users/button' %>

app/views/users/_button.html.erb
<div class='button_section'>

  <% if @count_time[0].created_at.strftime("%Y年%m月%d日") == Date.current.strftime("%Y年%m月%d日") %>
      <input type="button" class="btn btn-secondary" value="登録済み" disabled>

  <% else %>
    <div class='register_btn'>
      <%= link_to '今日の学習時間を登録', new_count_time_path, class:'register_link' %>
    </div>
  <% end %>
  <button class='user_btn'>
    <%= link_to '学習開始日の登録', new_start_day_path, class:'register_link' %>
  </button>
  <button class='user_btn'>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class:'user_link' %>
  </button>
</div>

app/views/users/_grass-graph.html.erb
<div class="github-link">
  <a href="https://github.com/suzy1031" target="_blank">
    <img src="https://grass-graph.moshimo.works/images/suzy1031.png?">
  </a>
</div>

app/views/users/_header.html.erb
<h2 class="progress_title">今週の進捗</h2>
<div class="progress" style="height: 20px;">
  <div id="answer_progress" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
    <%= controller.percent_in_week.round(1) %>%
  </div>
</div>
<div class="progress_percent_in_week">
  <a class="progress_a_week_counts"><%= controller.this_week_counts %>時間</a>
  あなたの進捗は<%=  controller.percent_in_week.round(1) %>パーセントです。
</div>

app/views/users/_nav.html.erb
<div class='header_notice'>
  <div class='header_notice__letter'>
    <% if Time.now.saturday? %>
      <%= controller.saturday_goal %>
    <% elsif Time.now.sunday? %>
      <%= controller.sunday_goal %>
    <% elsif Time.now.monday? %>
      <%= controller.monday_goal %>
    <% else %>
      <%= controller.otherDay_goal %>
    <% end %>
    <p>先週の学習時間は<%= controller.last_week_counts %>時間でした!</p>
    <p><%= controller.performance_this_year %></p>
  </div>
</div>

app/views/users/_section.html.erb
<% @start_day.each do |start_day| %>
  <div class='section'>
    <h3>あなたの学習開始日</h3>
    <h5>
      <%= start_day.start_day.strftime("%Y年%m月%d日") %>
    </h5>
  </div>
  <div class='section'>
    <h3>積み上げた日数</h3>
    <h5>
      <%= (Date.today - start_day.start_day.to_date).to_i %>日
    </h5>
  </div>
<% end %>
<div class='section'>
  <h3>トータル学習時間</h3>
  <h5><%= @count_hour.to_f %>時間</h5>
</div>

app/views/users/_stop-watch.html.erb
<div class="stop_watch">
  <div id="clock"> 00:00:00</div>
  <form>
    <input type="button" id="start"  class="btn btn-success" value="Start">
    <input type="button" id="stop" class="btn btn-secondary" value="Stop" disabled>
    <input type="button" id="restart" class="btn btn-info" value="Restart" disabled>
    <input type="button" id="reset" class="btn btn-danger" value="Reset" disabled>
  </form>
</div>

app/views/users/_table.html.erb
<div class='section'>
  <h3>昨日までの学習時間</h3>
  <table>
    <tr>
      <th>日付</th>
      <th>時間</th>
    </tr>
    <% @count_time.each do |count_time| %>
      <tr>
        <td><%= count_time.created_at.to_date %></td>
        <td><%= link_to edit_count_time_path(count_time), method: :get do %><%= count_time.count_hour %>時間<% end %></td>
        <td><%= link_to '削除', count_time_path(count_time), method: :delete, data: { confirm: "本当に削除しますか?" } %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<header>
  <%= render 'users/stop-watch' %>
  <%= render 'users/header' %>
</header>
<nav>
  <%= render 'users/nav' %>
</nav>
<main>
  <div class='container'>
    <article class='l_container'>
      <section class='m_container'>
        <%= render 'users/section' %>
        <%= render 'users/table' %>
      </section>
    </article>
    <aside class='m_container_right'>
      <%= render 'users/aside' %>
      <div class='year_count_table'>
        <h3>年ごとの合計学習時間</h2>
        <table>
          <th>年</th>
          <th>合計時間</th>
          <% controller.a_year_counts.each do |key,value| %>
            <tr>
              <td><%= key %></td>
              <td><%= "#{value.to_s(:delimited, delimiter: ',')}時間" %></td>
            </tr>
          <% end %>
        </table>
      </div>
    </aside>
  </div>
  <%= render 'users/grass-graph' %>
</main>